/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomSyncStatus = IDL.Record({
  'completedCount' : IDL.Nat,
  'exists' : IDL.Bool,
  'lastSyncTime' : IDL.Int,
});
export const RoomSurpriseState = IDL.Record({
  'creatorSurpriseId' : IDL.Text,
  'exists' : IDL.Bool,
  'joinerSurpriseId' : IDL.Text,
});

export const idlService = IDL.Service({
  'checkRoomSyncStatus' : IDL.Func([IDL.Text], [RoomSyncStatus], ['query']),
  'createRoom' : IDL.Func([], [IDL.Text], []),
  'getRoomSurprises' : IDL.Func([IDL.Text], [RoomSurpriseState], ['query']),
  'joinRoom' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'updateRoleSurprise' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateRoomState' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomSyncStatus = IDL.Record({
    'completedCount' : IDL.Nat,
    'exists' : IDL.Bool,
    'lastSyncTime' : IDL.Int,
  });
  const RoomSurpriseState = IDL.Record({
    'creatorSurpriseId' : IDL.Text,
    'exists' : IDL.Bool,
    'joinerSurpriseId' : IDL.Text,
  });
  
  return IDL.Service({
    'checkRoomSyncStatus' : IDL.Func([IDL.Text], [RoomSyncStatus], ['query']),
    'createRoom' : IDL.Func([], [IDL.Text], []),
    'getRoomSurprises' : IDL.Func([IDL.Text], [RoomSurpriseState], ['query']),
    'joinRoom' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'updateRoleSurprise' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateRoomState' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };